openapi: 3.2.0
info:
  title: V1 Lytics Metric API
  version: 1.0.0
  description: 'The Lytics API is a _restful_ *JSON* api that includes:

    * *Data Collection* api''s for collection, and upload of custom data.'
servers:
- url: https://api.lytics.io
tags:
- name: Metric
  description: 'The Metric API provides access to a variety of metrics that are recorded

    in the Lytics platform. With this API, you can access segment-size metrics,

    events received per-hour, as well as many workflow specific metrics.'
paths:
  /api/metric/:
    get:
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MetricModel'
              examples:
                response:
                  value:
                    data:
                    - name: sample-request
                      dimension: segsize
                      dimension_id: abc123
                      dimension_type: size
                      range: 2d
                      aggregation: max
                      interval: 2h
                      is_cached: true
                      values:
                      - value: 0
                        ts: '1525231674371'
                      - value: 100
                        ts: '1525238874371'
                      - value: 200
                        ts: '1525246074371'
                      - value: 300
                        ts: '1525253274371'
                      - value: 400
                        ts: '1525260474371'
                      - value: 500
                        ts: '1525267674371'
                      - value: 600
                        ts: '1525274874371'
                      - value: 700
                        ts: '1525282074371'
                      - value: 800
                        ts: '1525289274371'
                      - value: 900
                        ts: '1525296474371'
                    message: success
                    status: 200
      security:
      - ApiKeyAuth: []
      summary: Metric
      operationId: Metric
      description: 'Fetch metrics by providing the arguments in the query-parameters


        ```sh

        curl "$LIOAPI/api/metric?keyspace=segsize&metric=web&name=my-metric" -s -H "Authorization: $LIOKEY" | jq ''.''

        ```'
      tags:
      - Metric
      parameters:
      - name: account_id
        in: query
        description: Your Lytics account ID.
        required: false
        schema:
          type: string
      - name: name
        in: query
        description: Name of the metric to return
        required: false
        example: my-metric
        schema:
          type: string
      - name: dimension
        in: query
        description: Value of supported dimension (segment, experience, stream, etc)
        required: true
        example: segment
        schema:
          type: string
      - name: dimension_id
        in: query
        description: 'ID for the specific item within dimension such as a segment ID. Tip: If the type is a segment you can use all_segments as the dimension id to get all segments for the account.'
        required: true
        example: abc123
        schema:
          type: string
      - name: dimension_type
        in: query
        description: Type of metric to be returned (size, converted, etc)
        required: true
        example: size
        schema:
          type: string
      - name: aggregation
        in: query
        description: Aggregation to apply to metrics (sum, max, min)
        required: false
        example: sum
        schema:
          type: string
      - name: interval
        in: query
        description: Duration to roll-up metrics (2h for roll-up into two-hour buckets). Intervals smaller than two hours are not recommended.
        required: false
        example: 2h
        schema:
          type: string
      - name: include_empty_rows
        in: query
        description: Passing true will include zero values in the response for every interval whether metrics were logged during that period or not.
        required: false
        example: 'false'
        schema:
          type: boolean
      - name: smooth
        in: query
        description: Smooth metrics using a moving-average function
        required: false
        example: 'true'
        schema:
          type: boolean
      - name: start_date
        in: query
        description: Fetch metrics after this date; both dates and relative-dates are supported
        required: false
        example: now-5w
        schema:
          type: string
      - name: end_date
        in: query
        description: Fetch metrics before this date; both dates and relative-dates are supported
        required: false
        example: now-1w
        schema:
          type: string
      - name: range
        in: query
        description: 'Time string used to calculate range from now (e.g "2h" will return the last 2 hours). This parameter cannot

          be used in conjunction with `start_date` and/or `end_date)`

          '
        required: false
        example: 2h
        schema:
          type: string
  /api/metric:
    post:
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MetricModel'
              examples:
                response:
                  value:
                    data:
                    - name: sample-request
                      dimension: segsize
                      dimension_id: abc123
                      dimension_type: size
                      range: 2d
                      aggregation: max
                      interval: 2h
                      is_cached: true
                      values:
                      - value: 0
                        ts: '1525231674371'
                      - value: 100
                        ts: '1525238874371'
                      - value: 200
                        ts: '1525246074371'
                      - value: 300
                        ts: '1525253274371'
                      - value: 400
                        ts: '1525260474371'
                      - value: 500
                        ts: '1525267674371'
                      - value: 600
                        ts: '1525274874371'
                      - value: 700
                        ts: '1525282074371'
                      - value: 800
                        ts: '1525289274371'
                      - value: 900
                        ts: '1525296474371'
                    message: success
                    status: 200
      security:
      - ApiKeyAuth: []
      summary: Metric
      operationId: Metrics
      description: 'Fetch metrics by providing the arguments in the request body


        ```sh

        # Example of segment-size metrics

        curl -s -XPOST "$LIOAPI/api/metric" \

        -H ''Content-type: application/json'' \

        -H "Authorization: $LIOKEY" \

        -d ''{

        "dimension": "segsize",

        "dimension_id": "abc123",

        "dimension_type": "size",

        "interval": "2h",

        "aggregation": "max",

        "start_date": "now-5d",

        "end_date": "now",

        "smooth": true

        }'' | jq ''.''


        # Example request of data collected from the default and email stream

        curl -s -XPOST "$LIOAPI/api/metric" \

        -H "Content-type: application/json" \

        -H "Authorization: $LIOKEY" \

        -d ''[{

        "dimension": "stream",

        "dimension_id": "default",

        "dimension_type": "size",

        "interval": "1h",

        "aggregation": "sum",

        "start_date": "now-1w",

        "end_date": "now"

        },

        {

        "dimension": "stream",

        "dimension_id": "email",

        "dimension_type": "size",

        "interval": "1h",

        "aggregation": "sum",

        "start_date": "now-2w",

        "end_date": "now"

        }]'' | jq ''.''


        ```'
      tags:
      - Metric
      parameters:
      - name: account_id
        in: query
        description: Your Lytics account ID.
        required: false
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                dimension:
                  description: Value of supported dimension (segment, experience, stream, etc)
                  type: string
                dimension_id:
                  description: 'ID for the specific item within dimension such as a segment ID. Tip: If the type is a segment you can use all_segments as the dimension id to get all segments for the account.'
                  type: string
                dimension_type:
                  description: Type of metric to be returned (size, converted, etc)
                  type: string
                interval:
                  description: Duration to roll-up metrics (2h for roll-up into two-hour buckets). Intervals smaller than two hours are not recommended.
                  type: string
                aggregation:
                  description: Aggregation to apply to metrics (sum, max, min)
                  type: string
                smooth:
                  description: Smooth metrics using a moving-average function
                  type: boolean
                include_empty_rows:
                  description: Passing true will include zero values in the response for every interval whether metrics were logged during that period or not.
                  type: boolean
                start_date:
                  description: Fetch metrics after this date; both dates and relative-dates are supported
                  type: string
                end_date:
                  description: Fetch metrics before this date; both dates and relative-dates are supported
                  type: string
              example:
                dimension: segsize
                dimension_id: default
                dimension_type: size
                interval: 2h
                aggregation: max
                startdate: now-5d
                enddate: now
components:
  schemas:
    MetricModel:
      type: object
      properties:
        data:
          type: array
          items:
            type: object
            properties:
              name:
                type: string
              dimension:
                type: string
              dimension_id:
                type: string
              dimension_type:
                type: string
              range:
                type: string
              aggregation:
                type: string
              interval:
                type: string
              is_cached:
                type: boolean
              values:
                type: array
                items:
                  type: object
                  properties:
                    value:
                      type: number
                    ts:
                      type: string
                  required:
                  - value
                  - ts
        message:
          type: string
        status:
          type: number
      example:
        data:
        - name: sample-request
          dimension: segsize
          dimension_id: abc123
          dimension_type: size
          range: 2d
          aggregation: max
          interval: 2h
          is_cached: true
          values:
          - value: 0
            ts: '1525231674371'
          - value: 100
            ts: '1525238874371'
          - value: 200
            ts: '1525246074371'
          - value: 300
            ts: '1525253274371'
          - value: 400
            ts: '1525260474371'
          - value: 500
            ts: '1525267674371'
          - value: 600
            ts: '1525274874371'
          - value: 700
            ts: '1525282074371'
          - value: 800
            ts: '1525289274371'
          - value: 900
            ts: '1525296474371'
        message: success
        status: 200
  securitySchemes:
    ApiKeyAuth:
      in: header
      name: Authorization
      type: apiKey
x-readme:
  explorer-enabled: true
  proxy-enabled: true
