openapi: 3.2.0
info:
  title: V1 Lytics Auth API
  version: 1.0.0
  description: 'The Lytics API is a _restful_ *JSON* api that includes:

    * *Data Collection* api''s for collection, and upload of custom data.'
servers:
- url: https://api.lytics.io
tags:
- name: Auth
  description: 'API for creation or storage of auth tokens. Most of these

    tokens are created from the Integrations/Imports setup for Lytics integrations.


    Additionally, api tokens can be created/managed from this endpoint.


    The oauth, config information are write only attributes that

    cannot be subsequently read from the api, and is stored encrypted.'
paths:
  /api/auth/{id}:
    get:
      responses:
        '200':
          description: JSON representation of Auth Resource in addition to representing its state in the JSON.
          headers: {}
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthModel'
              examples:
                response:
                  value:
                    status: success
                    data:
                      account_id: 4f7b525bdba058fc096757a6
                      id: 1b53b88a06b418b07d601b6f57b8eb40
                      provider_id: 26cae7718c32180a7a0f8e19d6d40a59
                      provider_name: Facebook
                      user_id: 4222fd7c8db7ebcb042e0547e3b4e128
      security:
      - ApiKeyAuth: []
      summary: Retrieve a Single Auth
      operationId: Retrieve a Single Auth
      description: 'This API is fairly special, as only the public portions of the auth model are

        returned, not all fields **config**, **oauth2token**, and **oathtoken** fields are

        never exposed.'
      tags:
      - Auth
      parameters:
      - name: account_id
        in: query
        description: Your Lytics account ID.
        required: false
        schema:
          type: string
      - name: id
        in: path
        description: ID of the Gist in the form of a hash.
        required: true
        schema:
          type: string
      - name: access_token
        in: query
        description: Lytics API access token.
        required: false
        schema:
          type: string
    post:
      responses:
        '201':
          description: JSON representation of Auth Resource in addition to representing its state in the JSON.
          headers: {}
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthModel'
              examples:
                response:
                  value:
                    status: success
                    data:
                      account_id: 4f7b525bdba058fc096757a6
                      id: 1b53b88a06b418b07d601b6f57b8eb40
                      provider_id: 26cae7718c32180a7a0f8e19d6d40a59
                      provider_name: Facebook
                      user_id: 4222fd7c8db7ebcb042e0547e3b4e128
      security:
      - ApiKeyAuth: []
      summary: Create Auth
      operationId: Create Auth
      description: 'Create an auth, would normally never be used via the api, the web admin

        Integrations section manages these.'
      tags:
      - Auth
      parameters:
      - name: account_id
        in: query
        description: Your Lytics account ID.
        required: false
        schema:
          type: string
      - name: id
        in: path
        description: ID of the Gist in the form of a hash.
        required: true
        schema:
          type: string
      - name: access_token
        in: query
        description: Lytics API access token.
        required: false
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                provider_id:
                  type: string
                config:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      value:
                        type: string
              example:
                provider_id: our_provider
                config:
                - name: apikey
                  value: value_that_will_get_encrypted
    put:
      responses:
        '200':
          description: JSON representation of Auth Resource in addition to representing its state in the JSON.
          headers: {}
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthModel'
              examples:
                response:
                  value:
                    status: success
                    data:
                      account_id: 4f7b525bdba058fc096757a6
                      id: 1b53b88a06b418b07d601b6f57b8eb40
                      provider_id: 26cae7718c32180a7a0f8e19d6d40a59
                      provider_name: Facebook
                      user_id: 4222fd7c8db7ebcb042e0547e3b4e128
      security:
      - ApiKeyAuth: []
      summary: Update Auth
      operationId: Update Auth
      description: ''
      tags:
      - Auth
      parameters:
      - name: account_id
        in: query
        description: Your Lytics account ID.
        required: false
        schema:
          type: string
      - name: id
        in: path
        description: ID of the Gist in the form of a hash.
        required: true
        schema:
          type: string
      - name: access_token
        in: query
        description: Lytics API access token.
        required: false
        schema:
          type: string
    delete:
      responses:
        '204':
          description: No Content
          headers: {}
      security:
      - ApiKeyAuth: []
      summary: Remove an Auth
      operationId: Remove an Auth
      description: 'Deleting an auth is a very special operation. If any work is running (imports, exports),

        it will remove the auth from those works and stop them.'
      tags:
      - Auth
      parameters:
      - name: account_id
        in: query
        description: Your Lytics account ID.
        required: false
        schema:
          type: string
      - name: id
        in: path
        description: ID of the Gist in the form of a hash.
        required: true
        schema:
          type: string
      - name: access_token
        in: query
        description: Lytics API access token.
        required: false
        schema:
          type: string
  /api/auth/createtoken:
    post:
      responses:
        '201':
          description: Created
          headers: {}
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthApiTokenModel'
              examples:
                response:
                  value:
                    status: success
                    data:
                      account_id: 4f7b525bdba058fc096757a6
                      id: 1b53b88a06b418b07d601b6f57b8eb40
                      provider_id: 26cae7718c32180a7a0f8e19d6d40a59
                      name: my-token-for-service-x
                      provider_name: Lytics
                      config:
                      - api_key: api_value
      security:
      - ApiKeyAuth: []
      summary: Auth Create Token
      operationId: Auth Create Token
      description: Create Lytics api tokens.
      tags:
      - Auth
      parameters:
      - name: account_id
        in: query
        description: Your Lytics account ID.
        required: false
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                expires:
                  type: string
                scopes:
                  type: array
                  items:
                    type: string
                name:
                  type: string
              example:
                expires: 100h
                scopes:
                - admin
                - data
                name: my-token-for-serivce-x
components:
  schemas:
    AuthApiTokenModel:
      type: object
      properties:
        status:
          type: string
        data:
          type: object
          properties:
            account_id:
              type: string
            id:
              type: string
            provider_id:
              type: string
            name:
              type: string
            provider_name:
              type: string
            config:
              type: array
              items:
                type: object
                properties:
                  api_key:
                    type: string
      example:
        status: success
        data:
          account_id: 4f7b525bdba058fc096757a6
          id: 1b53b88a06b418b07d601b6f57b8eb40
          provider_id: 26cae7718c32180a7a0f8e19d6d40a59
          name: my-token-for-service-x
          provider_name: Lytics
          config:
          - api_key: api_value
    AuthModel:
      type: object
      properties:
        status:
          type: string
        data:
          type: object
          properties:
            account_id:
              type: string
            id:
              type: string
            provider_id:
              type: string
            provider_name:
              type: string
            user_id:
              type: string
      example:
        status: success
        data:
          account_id: 4f7b525bdba058fc096757a6
          id: 1b53b88a06b418b07d601b6f57b8eb40
          provider_id: 26cae7718c32180a7a0f8e19d6d40a59
          provider_name: Facebook
          user_id: 4222fd7c8db7ebcb042e0547e3b4e128
  securitySchemes:
    ApiKeyAuth:
      in: header
      name: Authorization
      type: apiKey
x-readme:
  explorer-enabled: true
  proxy-enabled: true
