openapi: 3.2.0
info:
  title: V1 Lytics Query API
  version: 1.0.0
  description: 'The Lytics API is a _restful_ *JSON* api that includes:

    * *Data Collection* api''s for collection, and upload of custom data.'
servers:
- url: https://api.lytics.io
tags:
- name: Query
  description: Schema management api to add/edit queries and user-fields.
paths:
  /api/query:
    get:
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QueryListModel'
              examples:
                response:
                  value:
                    status: success
                    data:
                    - id: abcdef123
                      updated: '2014-10-30T21:01:06.493Z'
                      created: '2014-10-30T21:01:06.493Z'
                      text: SELECT ...
      security:
      - ApiKeyAuth: []
      summary: Query List
      operationId: Query List
      description: List of all queries
      tags:
      - Query
    post:
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QueryListModel'
              examples:
                response:
                  value:
                    status: success
                    data:
                    - id: abcdef123
                      updated: '2014-10-30T21:01:06.493Z'
                      created: '2014-10-30T21:01:06.493Z'
                      text: SELECT ...
      security:
      - ApiKeyAuth: []
      summary: Query Upsert
      operationId: Query Upsert
      description: 'Uses ALIAS name inside parsed query for ID, and either creates/updates a query.


        **CHANGE NOTIFICATION** This api in the past has returned a single object

        but is changing to return an array of query objects (because posted QL text

        may contain more than one statement). To get the old behavior

        of single object pass *version=old*.


        ```sh

        # new version, will be default in Sept 2017.

        curl -s -XPOST "https://api.lytics.io/api/query?version=new" \

        -H "Authorization: $LIOKEY" \

        --data-binary @your_file.lql


        # old version, returns object

        curl -s -XPOST "https://api.lytics.io/api/query?version=old" \

        -H "Authorization: $LIOKEY" \

        --data-binary @your_file.lql


        ```'
      tags:
      - Query
      parameters:
      - name: account_id
        in: query
        description: Your Lytics account ID.
        required: false
        schema:
          type: string
      - name: version
        in: query
        description: Use the "new" array based response or "old" object.
        required: false
        example: old
        schema:
          type: string
  /api/query/{idOrAlias}:
    get:
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QueryModel'
              examples:
                response:
                  value:
                    status: success
                    data:
                      id: abcdef123
                      updated: '2014-10-30T21:01:06.493Z'
                      created: '2014-10-30T21:01:06.493Z'
                      text: SELECT ...
      security:
      - ApiKeyAuth: []
      summary: Query Fetch
      operationId: Query Fetch
      description: Get single query by *ALIAS OR ID*
      tags:
      - Query
      parameters:
      - name: account_id
        in: query
        description: Your Lytics account ID.
        required: false
        schema:
          type: string
      - name: idOrAlias
        in: path
        description: Alias of query
        required: true
        example: web
        schema:
          type: string
    delete:
      responses:
        '204':
          description: No Content
          headers: {}
      security:
      - ApiKeyAuth: []
      summary: Query Delete
      operationId: Query Delete
      description: Delete A query by idOrAlias.
      tags:
      - Query
      parameters:
      - name: account_id
        in: query
        description: Your Lytics account ID.
        required: false
        schema:
          type: string
      - name: idOrAlias
        in: path
        description: Alias of query
        required: true
        example: web
        schema:
          type: string
  /api/query/_validate:
    post:
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QueryModel'
              examples:
                response:
                  value:
                    status: success
                    data:
                      id: abcdef123
                      updated: '2014-10-30T21:01:06.493Z'
                      created: '2014-10-30T21:01:06.493Z'
                      text: SELECT ...
      security:
      - ApiKeyAuth: []
      summary: Query Validation
      operationId: Query Validation
      description: 'Upload a query for syntax validation only.


        Optionally, a *segments=true* parameter can be passed that

        will validate this query both for syntax, as well as checking

        that it doesn''t invalidate existing segments. If a segment

        uses a field that this query is about to remove/alter such

        that the segment is no longer valid, this will warn.


        ```sh


        # validate query syntax

        curl -s -XPOST "https://api.lytics.io/api/query/_validate" \

        -H "Authorization: $LIOKEY" \

        -H "Content-Type: text/plain" \

        --data-binary @your_file.lql


        # validate query syntax AND segments still valid

        curl -s -XPOST "https://api.lytics.io/api/query/_validate?segments=true" \

        -H "Authorization: $LIOKEY" \

        -H "Content-Type: text/plain" \

        --data-binary @your_file.lql


        ```'
      tags:
      - Query
      parameters:
      - name: account_id
        in: query
        description: Your Lytics account ID.
        required: false
        schema:
          type: string
      - name: version
        in: query
        description: Use the "new" array based response or "old" object.
        required: false
        example: old
        schema:
          type: string
  /api/query/_test:
    post:
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QueryModel'
              examples:
                response:
                  value:
                    status: success
                    data:
                      id: abcdef123
                      updated: '2014-10-30T21:01:06.493Z'
                      created: '2014-10-30T21:01:06.493Z'
                      text: SELECT ...
      security:
      - ApiKeyAuth: []
      summary: Query Test Evaluation
      operationId: Query Test Evaluation
      description: 'Upload a query AND data to see how it will be interpreted.


        ```sh


        # add any name/value paris to query string param for data input

        # then upload query and get evaluation response

        curl -s -XPOST "https://api.lytics.io/api/query/_test?name=value" \

        -H "Authorization: $LIOKEY" \

        -H "Content-Type: text/plain" \

        --data-binary @your_file.lql


        ```'
      tags:
      - Query
components:
  schemas:
    QueryModel:
      type: object
      properties:
        status:
          type: string
        data:
          type: object
          properties:
            id:
              type: string
            updated:
              type: string
            created:
              type: string
            text:
              type: string
      example:
        status: success
        data:
          id: abcdef123
          updated: '2014-10-30T21:01:06.493Z'
          created: '2014-10-30T21:01:06.493Z'
          text: SELECT ...
    QueryListModel:
      type: object
      properties:
        status:
          type: string
        data:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
              updated:
                type: string
              created:
                type: string
              text:
                type: string
      example:
        status: success
        data:
        - id: abcdef123
          updated: '2014-10-30T21:01:06.493Z'
          created: '2014-10-30T21:01:06.493Z'
          text: SELECT ...
  securitySchemes:
    ApiKeyAuth:
      in: header
      name: Authorization
      type: apiKey
x-readme:
  explorer-enabled: true
  proxy-enabled: true
